version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "SqlServer2022!"
      ACCEPT_EULA: "Y"
      TZ: "Australia/Melbourne"
    ports:
      - "1433:1433"
    restart: unless-stopped
    volumes:
      - sqlserver_data:/var/opt/mssql
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - drivehub-network

  drivehub:
    image: drivehub-image
    container_name: drivehub
    ports:
      - "5555:8080"
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      TZ: "Australia/Melbourne"
    volumes:
      - drivehub_data:/root/.aspnet/DataProtection-Keys
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - drivehub-network

  admin:
    image: admin-image
    container_name: portal
    ports:
      - "5556:8080"
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      TZ: "Australia/Melbourne"
    volumes:
      - drivehub_data:/root/.aspnet/DataProtection-Keys
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - drivehub-network

networks:
  drivehub-network:

volumes:
  sqlserver_data:
  drivehub_data:
    driver: local
