version: '3.8'

services:

  drivehub:
    image: drivehub-image
    container_name: drivehub
    ports:
      - "5555:8080"
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      TZ: "Australia/Melbourne"
    volumes:
      - drivehub_data:/root/.aspnet/DataProtection-Keys
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  admin:
    image: admin-image
    container_name: portal
    ports:
      - "5556:8080"
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      TZ: "Australia/Melbourne"
    volumes:
      - drivehub_data:/root/.aspnet/DataProtection-Keys
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

volumes:
  drivehub_data:
    driver: local
